# Generated by Django 4.1.4 on 2023-01-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=512, unique=True)),
                ("email", models.CharField(max_length=512, unique=True)),
                ("twitter", models.CharField(max_length=512, null=True, unique=True)),
                ("telegram", models.CharField(max_length=512, null=True, unique=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("wallet", models.CharField(max_length=512, null=True, unique=True)),
                ("dnft", models.IntegerField(default=0, null=True)),
                ("dp", models.IntegerField(default=0, null=True)),
                ("password", models.CharField(max_length=512)),
                ("photo", models.CharField(blank=True, max_length=512, null=True)),
                ("role", models.IntegerField(default=0, null=True)),
                ("disabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
